### ISSUE TITLE
the pagination feature is broken at rbd status page

### ISSUE THREAD

**Issue by ywang19** [01org/virtual-storage-manager#495]
if there are hundreds of rbd volumes, the expandable table will make the ui awful

**Comment by flyingfish007** [comment]
#500 
Now I add the pagination setting on User Setting page. You can change the items per page.
At present, there is pagination on rbd status page.

**Comment by flyingfish007** [comment]
#506 
change the pagination from user page to setting page

**Comment by flyingfish007** [comment]
#507 
lack of comma cause the UI error
