### ISSUE TITLE
there is no cluster_manifest supplied during the installation

### ISSUE THREAD

**Issue by oguzy** [01org/virtual-storage-manager#504]
Seems there are two files that can be used: 

virtual-storage-manager/source/vsm/bin/cluster_manifest
virtual-storage-manager/source/vsm-deploy/cluster_manifest

None is at the $PATH so whenever cluster_manifest is called, it is giving errors.

Which is the correct file to be used during install.sh and vsm-installer?

**Comment by ywang19** [comment]
there are not, the expected cluster.manifest will be at ./manifest/<vsm_controller>/cluster.manifest

**Comment by oguzy** [comment]
the cluster.manifest file and the cluster_manifest script are different things.
I am talking about https://github.com/01org/virtual-storage-manager/blob/master/source/vsm-deploy/cluster_manifest this file which is called https://github.com/01org/virtual-storage-manager/blob/master/source/vsm-deploy/vsm-installer#L50 for ex.

**Comment by flyingfish007** [comment]
When we pack the four packages of vsm project, the file under virtual-storage-manager/source/vsm/bin/cluster_manifest will be packed into vsm package(/usr/loca/bin/cluster_manifest). So after you have installed the vsm package, under the folder /user/local/bin, you will see the file cluster_manifest.

PATH_N="**/usr/local/bin**:/usr/bin:/usr/local/sbin:/usr/sbin"
In the install.sh script, the PATH has been append with "PATH_N" which defines in the script. If you install the vsm package corrected, I think you can call the cluster_manifest script.

**Comment by oguzy** [comment]
Unfortunately the vsm deb package at the vsm-dependencies repo does not contain the cluster_manifest file. I had to cp it manually.

**Comment by flyingfish007** [comment]
Did you package the vsm package by yourself or download from the release packages?

**Comment by oguzy** [comment]
Download from the release package

On Wed, May 11, 2016 at 9:52 AM, flyingfish007 <notifications@github.com>
wrote:

> Did you package the vsm package by yourself or download from the release
> packages?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/01org/virtual-storage-manager/issues/504#issuecomment-218376851>
>



-- 
Oğuz Yarımtepe
http://about.me/oguzy

**Comment by flyingfish007** [comment]
I have checked the release package 2.1.0-336-ubuntu14.tar.gz. There is cluster_manifest in vsm_2.1.0-336_amd64.deb(/usr/local/bin/cluster_manifest).
