### ISSUE TITLE
what is the default version of ceph when deploy ceph using vsm

### ISSUE THREAD

**Issue by JadenGuo** [01org/virtual-storage-manager#561]
what is the default version of ceph when deploy ceph cluster using vsm,does it allowed me to change the setting so I can deploy any version of ceph like hammer?What's the method?

**Comment by flyingfish007** [comment]
Hi @JadenGuo ,
The vsm doesn't assign the version of ceph to deploy. If you don't add the repo for centos or list for ubuntu, I think the version of ceph is firefly.
So if you want to deploy the version which you want, you just only add the repo or list of ceph by youself.

**Comment by JadenGuo** [comment]
one more question, if I deploy my cluster using vsm, can I modify or reset it using ceph-deploy?

**Comment by flyingfish007** [comment]
What's the meaning of reset it?
The vsm is a GUI tool for user to operate ceph cluster easily. If you deploy the ceph by vsm, you also can operate it by CLI.
In turn, vsm can manage the ceph cluster which is deployed by ceph-deploy.

**Comment by JadenGuo** [comment]
so I can manage a exist ceph cluster using vsm?

**Comment by flyingfish007** [comment]
yes, you can. The vsm provide the function of "import cluster".

**Comment by JadenGuo** [comment]
thanks a lot
